[[inputs.mqtt_consumer]]
  servers = ["tcp://broker.hivemq.com:1883"]
  topics = ["faizrahmadani-digitalskola/iot/energy", "faizrahmadani-digitalskola/iot/room", "faizrahmadani-digitalskola/iot/motor"]
  qos = 0
  data_format = "value"
  data_type = "float"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "mytoken"
  organization = "kampus"
  bucket = "iot"
